version: '3'

services:
  gshirachin-app:
    # ここを好きな名前(まだそのPCで使ってない名前)に変更
    build: .
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - 8000:8000
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - DATABASE_URL=mysql://root@db/demo
    depends_on:
      - db

  db:
    container_name: mysql_host2 #変えた0701
    image: mysql:8.0
    platform: linux/x86_64
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-authentication-plugin=mysql_native_password
    ports:
      - 33306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'demo' # たぶんここもすきな名前に変更してよさそうやけど変えなくていい。変更するならenvironment:の- DATABASE_URL=mysql://root@db/demoのdomoの部分も変更する。
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql_data2:/var/lib/mysql # ここを変更。例：mysql_dataからmysql_data2へ。最後の行のvolumes:と合わせる

  phpmyadmin:
    container_name: phpmyadmin_host2 #変えた0701
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql_host
      PMA_USER: root

volumes:
  mysql_data2: # ここを変更。例：mysql_dataからmysql_data2へ
